### ISSUE TITLE
11-30 full languages

### ISSUE THREAD

**Issue by KJablonski08** [esquire-code/0.how-to-use#1]
A lot of developers don't consider HTML/CSS to be programming languages - they are just structure and styling. They are critical to know, but we might want to consider breaking these into their own section to keep legitimate: 
**HTML and CSS are actually not technically programming languages; they're just page structure and style information. But before moving on to JavaScript and other true languages, you need to know the basics of HTML and CSS, as they are on the front end of every web page and application**

We might want to consider: structure & styling language: HTML/CSS

**Comment by chris-a-phillips** [comment]
I'm cool with changing this. I agree with what you're saying and I thought about this before, but I just wanted to start building everything out. I think as this gets more completed and there is a "public" file visualizer, chart, or way to see how things are organized, this can be cemented as something else.
